# Generated by Django 5.2.13 on 2026-04-22 03:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_alter_post_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='background_color',
            field=models.CharField(default='#0F172A', max_length=7, validators=[django.core.validators.RegexValidator(message='Use a valid 6-digit hex color, for example #005A43.', regex='^#[0-9A-Fa-f]{6}$')]),
        ),
        migrations.AddField(
            model_name='post',
            name='text_color',
            field=models.CharField(default='#F8FAFC', max_length=7, validators=[django.core.validators.RegexValidator(message='Use a valid 6-digit hex color, for example #005A43.', regex='^#[0-9A-Fa-f]{6}$')]),
        ),
        migrations.AlterField(
            model_name='post',
            name='content_type',
            field=models.CharField(choices=[('image', 'Image/PDF Slide'), ('video', 'Video Slide'), ('custom', 'Rich Text'), ('html', 'Custom HTML')], default='image', max_length=10),
        ),
    ]
