# Generated by Django 5.2.13 on 2026-04-22 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_post_background_color_post_text_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='media_revision',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='media_variants',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='post',
            name='preview_image',
            field=models.FileField(blank=True, null=True, upload_to='renditions/'),
        ),
    ]
