# Generated by Django 5.2.13 on 2026-04-23 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0018_post_image_edit_settings_and_siteappearance_favorites'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='youtube_quality',
            field=models.CharField(choices=[('auto', 'Auto'), ('medium', '360p'), ('large', '480p'), ('hd720', '720p'), ('hd1080', '1080p'), ('highres', 'Best available / 4K')], default='auto', max_length=20),
        ),
        migrations.AddField(
            model_name='post',
            name='youtube_show_captions',
            field=models.BooleanField(default=False),
        ),
    ]
