# Generated by Django 5.2.13 on 2026-09-23 17:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0041_transit_animation_controls'),
    ]

    operations = [
        migrations.AddField(
            model_name='transitdashboardconfig',
            name='route_opacity_percent',
            field=models.PositiveSmallIntegerField(default=100, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
