# Generated by Django 5.2.13 on 2026-09-29 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0042_transit_route_opacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteappearancesettings',
            name='public_base_url',
            field=models.URLField(default='http://pi-serv.rex-powan.ts.net', max_length=2048),
        ),
    ]
