# Generated by Django 5.2.13 on 2026-10-01 00:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0043_site_public_base_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occurred_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('username', models.CharField(max_length=150)),
                ('action', models.CharField(max_length=160)),
                ('target', models.CharField(blank=True, max_length=300)),
                ('outcome', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('submitted', 'Submitted')], max_length=20)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-occurred_at', '-pk'],
            },
        ),
    ]
