"""
Django settings for sliderCMS project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
import socket
from sliderCMS.runtime import DATA_DIR, DATELINE_PATH
import secrets


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
DATA_DIR.mkdir(parents=True, exist_ok=True)
LOG_DIR = DATA_DIR / "logs"
LOG_DIR.mkdir(parents=True, exist_ok=True)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SLIDERCMS_SECRET_KEY')
if not SECRET_KEY:
    key_path = DATA_DIR / '.secret_key'
    try:
        fd = os.open(key_path, os.O_WRONLY | os.O_CREAT | os.O_EXCL, 0o600)
    except FileExistsError:
        pass
    else:
        with os.fdopen(fd, 'w') as key_file:
            key_file.write(secrets.token_urlsafe(64))
    SECRET_KEY = key_path.read_text().strip()

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('SLIDERCMS_DEBUG', '1').lower() in {'1', 'true', 'yes'}
SLIDERCMS_UPDATE_REPOSITORY = os.getenv('SLIDERCMS_UPDATE_REPOSITORY', '')
SLIDERCMS_UPDATE_BRANCH = os.getenv('SLIDERCMS_UPDATE_BRANCH', 'main')
SLIDERCMS_UPDATES_ENABLED = os.getenv('SLIDERCMS_UPDATES_ENABLED', '0') == '1'


def _split_env_list(raw_value):
    return [item.strip() for item in (raw_value or "").split(",") if item.strip()]


def _dedupe(items):
    ordered_items = []
    seen = set()
    for item in items:
        if item and item not in seen:
            ordered_items.append(item)
            seen.add(item)
    return ordered_items


def _origin_for_host(host, scheme):
    if not host or host in {"*", "0.0.0.0"}:
        return None
    if host.startswith("."):
        host = f"*{host}"
    return f"{scheme}://{host}"


DEFAULT_ALLOWED_HOSTS = [
    "localhost",
    "127.0.0.1",
    "[::1]",
    "0.0.0.0",
    socket.gethostname(),
    socket.getfqdn(),
    ".ts.net",
]

ENV_ALLOWED_HOSTS = _split_env_list(os.getenv("SLIDERCMS_ALLOWED_HOSTS"))

ALLOWED_HOSTS = _dedupe(DEFAULT_ALLOWED_HOSTS + ENV_ALLOWED_HOSTS)


DEFAULT_CSRF_TRUSTED_ORIGINS = _dedupe([
    "http://localhost",
    "https://localhost",
    "http://127.0.0.1",
    "https://127.0.0.1",
    "http://[::1]",
    "https://[::1]",
    "http://*.ts.net",
    "https://*.ts.net",
    _origin_for_host(socket.gethostname(), "http"),
    _origin_for_host(socket.gethostname(), "https"),
    _origin_for_host(socket.getfqdn(), "http"),
    _origin_for_host(socket.getfqdn(), "https"),
])

CSRF_TRUSTED_ORIGINS = _dedupe(
    DEFAULT_CSRF_TRUSTED_ORIGINS
    + [
        origin
        for host in ENV_ALLOWED_HOSTS
        for origin in (_origin_for_host(host, "http"), _origin_for_host(host, "https"))
        if origin
    ]
    + _split_env_list(os.getenv("SLIDERCMS_CSRF_TRUSTED_ORIGINS"))
)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "posts", #image upload
    "accounts", #creating new users
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'posts.middleware.ActivityLogMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'posts.middleware.MediaCacheControlMiddleware',
]

# Send only this site's origin on cross-origin requests, as required by public map tile services.
SECURE_REFERRER_POLICY = 'strict-origin-when-cross-origin'

ROOT_URLCONF = 'sliderCMS.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'posts.context_processors.site_appearance',
            ],
        },
    },
]

WSGI_APPLICATION = 'sliderCMS.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': DATA_DIR / 'db.sqlite3',
        # Wait for short concurrent writes, especially during site restore.
        'OPTIONS': {
            'timeout': float(os.getenv('SLIDERCMS_SQLITE_TIMEOUT', '30')),
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = os.getenv('SLIDERCMS_TIME_ZONE', 'America/New_York')

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'templates/static'),
]
STATIC_ROOT = DATA_DIR / 'static'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# media files (uploaded by users)
MEDIA_URL = "/media/"
MEDIA_ROOT = DATA_DIR / "media"

#login settings
LOGIN_URL = '/accounts/login/'
LOGIN_REDIRECT_URL = 'home'
LOGOUT_REDIRECT_URL = 'home'

#new users
EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
EMAIL_FILE_PATH = DATA_DIR / 'emails'

#celery tasks
CELERY_BROKER_URL = "redis://localhost:6379/0"  # Redis server URL
CELERY_RESULT_BACKEND = "redis://localhost:6379/0"  # Store task results
CELERY_TIMEZONE = TIME_ZONE
CELERY_WORKER_PREFETCH_MULTIPLIER = 1

from celery.schedules import crontab  # Used for scheduled tasks

CELERY_BEAT_SCHEDULE = {
    "apply_screen_power_schedule_every_minute": {
        "task": "posts.tasks.apply_screen_power_schedule",
        "schedule": crontab(minute="*"),
        "options": {"expires": 60},
    },
}

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "{asctime} {levelname} {name} {message}",
            "style": "{",
        },
    },
    "handlers": {
        "upload_errors_file": {
            "class": "logging.handlers.RotatingFileHandler",
            "filename": LOG_DIR / "upload_errors.log",
            "maxBytes": 1024 * 1024,
            "backupCount": 5,
            "formatter": "verbose",
        },
        "screen_power_file": {
            "class": "logging.handlers.RotatingFileHandler",
            "filename": LOG_DIR / "screen_power.log",
            "maxBytes": 1024 * 1024,
            "backupCount": 5,
            "formatter": "verbose",
        },
    },
    "loggers": {
        "upload_errors": {
            "handlers": ["upload_errors_file"],
            "level": "INFO",
            "propagate": True,
        },
        "screen_power": {
            "handlers": ["screen_power_file"],
            "level": "INFO",
            "propagate": False,
        },
    },
}
