from django.urls import path
from django.views.generic import RedirectView
from . import views
from . import update_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('settings/updates/check/', update_views.update_check, name='update_check'),
    path('settings/updates/install/', update_views.update_install, name='update_install'),
    #path("", HomePageView.as_view(), name="home"),
    path("add-slide/", views.upload_image, name="add_slide"),
    path("post/", RedirectView.as_view(pattern_name="add_slide", permanent=False)),
    path("slide-library/", views.all_images_view, name="manage_slides"),
    path("manage-slides/", RedirectView.as_view(pattern_name="manage_slides", permanent=False)),
    path("allimages/", RedirectView.as_view(pattern_name="manage_slides", permanent=False)),
    path("slide-library/reorder/", views.reorder_slides, name="reorder_slides"),
    path("slide-library/edit-image/<str:pk>/", views.edit_slide_image, name="edit_slide_image"),
    path("slide-library/edit-html/<str:pk>/", views.edit_html_slide, name="edit_html_slide"),
    path("slide-library/edit-rich-text/<str:pk>/", views.edit_rich_text_slide, name="edit_rich_text_slide"),
    path("slide-library/edit-google-slides/<str:pk>/", views.edit_google_slides_slide, name="edit_google_slides_slide"),
    path("delete_image/<str:pk>/", views.delete_image, name="delete_image"), 
    path("update-title/<str:pk>/", views.update_slide_title, name="update_slide_title"),
    path("update-duration/<str:pk>/", views.update_slide_duration, name="update_slide_duration"),
    path("update-visibility/<str:pk>/", views.update_slide_visibility, name="update_slide_visibility"),
    path("generated-slides/<str:scraper_name>/", views.update_generated_slide_config, name="update_generated_slide_config"),
    path("weather-slide-settings/", views.update_weather_slide_config, name="update_weather_slide_config"),
    path("calendar-slide-settings/", views.update_calendar_slide_config, name="update_calendar_slide_config"),
    path("transit-dashboard-settings/", views.update_transit_dashboard_config, name="update_transit_dashboard_config"),
    path("empty-display-settings/", views.update_empty_display_config, name="update_empty_display_config"),
    path("breaking-news-ticker-settings/", views.update_breaking_news_ticker_config, name="update_breaking_news_ticker_config"),
    path("slidedisplay/", views.slidedisplay, name="slidedisplay"),
    path("slidedisplay/slide/<int:pk>/paused/", views.paused_post_view, name="paused_post_view"),
    path("slidedisplay/breaking-news-feed/", views.breaking_news_ticker_feed, name="breaking_news_ticker_feed"),
    path("slidedisplay/dateline/", views.read_dateline, name="dateline"),
    path("slidedisplay/dateline/paused/", views.read_dateline, {"paused": True}, name="dateline_paused"),
    path("slidedisplay/dateline/getjson/", views.fetch_json_view, name="getjson"),
    path("slidedisplay/weatherview/", views.weather_view, name="weather_view"),
    path("slidedisplay/weatherview/paused/", views.weather_view, {"paused": True}, name="weather_view_paused"),
    path("slidedisplay/calendar/", views.calendar_view, name="calendar_view"),
    path("slidedisplay/calendar/paused/", views.calendar_view, {"paused": True}, name="calendar_view_paused"),
    path("slidedisplay/transit/", views.transit_view, name="transit_view"),
    path("slidedisplay/transit/paused/", views.transit_view, {"paused": True}, name="transit_view_paused"),
    path("transit/mobile/", views.transit_view, {"paused": True, "mobile": True}, name="transit_mobile"),
    path("transit/mobile/map-data/", views.transit_map_data, {"mobile": True}, name="transit_mobile_map_data"),
    path("transit/mobile/live-data/", views.transit_live_data, {"mobile": True}, name="transit_mobile_live_data"),
    path("transit/mobile/qr.png", views.transit_mobile_qr, name="transit_mobile_qr"),
    path("add-slide/qr/", views.rich_text_qr, name="rich_text_qr"),
    path("slidedisplay/transit/map-data/", views.transit_map_data, name="transit_map_data"),
    path("slidedisplay/transit/live-data/", views.transit_live_data, name="transit_live_data"),
    path("settings/", views.settings_view, name="settings"),
    path("manage-users/", RedirectView.as_view(pattern_name="settings", permanent=False)),
    path("settings/site-migration/export/", views.export_site_migration_view, name="export_site_migration"),
    path("settings/site-migration/import/", views.import_site_migration_view, name="import_site_migration"),
    path("settings/appearance/", views.update_site_appearance, name="update_site_appearance"),
    path("screen-power-schedule/", views.update_screen_power_schedule, name="update_screen_power_schedule"),
    path("reset-user-password/", views.reset_user_password, name="reset_user_password"),
    path("toggle-superuser/<str:pk>/", views.toggle_superuser, name="toggle_superuser"),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
